options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Authenticate Docker with Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker europe-north1-docker.pkg.dev

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-north1-docker.pkg.dev/skavaair/frontend:latest', './frontend']

  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-north1-docker.pkg.dev/skavaair/backend:latest', './backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-north1-docker.pkg.dev/skavaair/frontend:latest']

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-north1-docker.pkg.dev/skavaair/backend:latest']

  # Set up kubectl with GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials skavaair-kube-cluster \
          --region europe-north1 \
          --project skavaair

  # Deploy Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']

images:
  - europe-north1-docker.pkg.dev/skavaair/frontend:latest
  - europe-north1-docker.pkg.dev/skavaair/backend:latest
