name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: skavaair
          install_components: 'kubectl'

      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${{ github.workspace }}/gcp-key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcp-key.json

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker Images
        run: |
          docker build -t gcr.io/skavaair/frontend ./frontend
          docker build -t gcr.io/skavaair/backend ./backend
          docker push gcr.io/skavaair/frontend
          docker push gcr.io/skavaair/backend

      - name: Set up GKE credentials
        run: gcloud container clusters get-credentials skavaair-kube-cluster --zone us-central1-a --project skavaair

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
