name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: skavaair
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker images
      run: |
        gcloud auth configure-docker europe-north1-docker.pkg.dev
        docker build -t europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest ./frontend
        docker build -t europe-north1-docker.pkg.dev/skavaair/backend/backend:latest ./backend
        docker push europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest
        docker push europe-north1-docker.pkg.dev/skavaair/backend/backend:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials skavaair-kube-cluster --region europe-north1

    - name: Deploy to GKE
      env:
        CLOUDSDK_COMPUTE_REGION: europe-north1
        CLOUDSDK_CONTAINER_CLUSTER: skavaair-kube-cluster
      run: |
        kubectl apply -f k8s/
