name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: skavaair
          export_default_credentials: true

      - name: Authenticate to GCP
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | jq '.' > ${{ github.workspace }}/gcp-key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcp-key.json

      - name: Set up GKE credentials
        run: |
          gcloud container clusters get-credentials skavaair-kube-cluster \
            --zone us-central1-a \
            --project skavaair

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
