name: Deploy to GKE

on:
  push:
    branches:
      - master  # Trigger on pushes to master branch (you can change this if necessary)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: skavaair  # Your Google Cloud project ID
          credentials_json: ${{ secrets.GCP_SA_NEW_KEY }}  # Your service account key stored in GitHub secrets

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin || true

      - name: Authenticate with gcloud using the service account key
        run: |
          echo "${{ secrets.GCP_SA_NEW_KEY }}" | base64 --decode > /tmp/gcp-key.json
          cat /tmp/gcp-key.json  # Debug step to verify key content
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials skavaair-kube-cluster --zone europe-north1 --project skavaair

      - name: Deploy frontend
        run: kubectl apply -f k8s/frontend-deployment.yaml

      - name: Deploy backend
        run: kubectl apply -f k8s/backend-deployment.yaml

      - name: Expose services
        run: kubectl apply -f k8s/frontend-service.yaml && kubectl apply -f k8s/backend-service.yaml
