name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: skavaair
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Artifact Registry authentication
        run: |
          mkdir -p ~/.docker
          echo '{"credHelpers":{"europe-north1-docker.pkg.dev":"gcloud"}}' > ~/.docker/config.json

      - name: Build and push frontend image
        run: |
          docker build -t europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest ./frontend
          docker push europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t europe-north1-docker.pkg.dev/skavaair/backend/backend:latest ./backend
          docker push europe-north1-docker.pkg.dev/skavaair/backend/backend:latest

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s
