name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: skavaair
          service_account_key: ${{ secrets.GCP_SA_NEW_KEY }}
          export_default_credentials: true

      - name: Set gcloud active account
        run: |
          ACCOUNT=$(gcloud config get-value account)
          echo "Active account: $ACCOUNT"
          gcloud config set account "$ACCOUNT"

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials skavaair-kube-cluster --zone europe-north1 --project skavaair

      - name: Deploy frontend
        run: kubectl apply -f k8s/frontend-deployment.yaml

      - name: Deploy backend
        run: kubectl apply -f k8s/backend-deployment.yaml

      - name: Expose services
        run: |
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/backend-service.yaml
