name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: skavaair
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker authentication
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build and push Frontend Docker image
        run: |
          docker build -t europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest ./frontend
          docker push europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest

      - name: Build and push Backend Docker image
        run: |
          docker build -t europe-north1-docker.pkg.dev/skavaair/backend/backend:latest ./backend
          docker push europe-north1-docker.pkg.dev/skavaair/backend/backend:latest

      - name: Set up kubeconfig
        run: |
          gcloud container clusters get-credentials skavaair-kube-cluster --region europe-north1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s
