name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: skavaair
      REGION: europe-north1
      CLUSTER: skavaair-kube-cluster

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 🔐 Auth via GitHub action (safe + no manual gcloud config)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # ☁️ Set up gcloud + kubectl
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'kubectl'

      # 🎯 Fetch GKE credentials (this fixes the "no cluster set" issue)
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Push Docker Images
        run: |
          gcloud auth configure-docker --quiet
          docker build -t gcr.io/${{ env.PROJECT_ID }}/frontend ./frontend
          docker build -t gcr.io/${{ env.PROJECT_ID }}/backend ./backend
          docker push gcr.io/${{ env.PROJECT_ID }}/frontend
          docker push gcr.io/${{ env.PROJECT_ID }}/backend

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
          kubectl get all
