name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: skavaair
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud authentication
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build and Push Docker images
        run: |
          docker build -t europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest ./frontend
          docker build -t europe-north1-docker.pkg.dev/skavaair/backend/backend:latest ./backend
          docker push europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest
          docker push europe-north1-docker.pkg.dev/skavaair/backend/backend:latest

      - name: Set up Kubeconfig
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: skavaair-kube-cluster
          location: europe-north1

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
