name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: skavaair
          install_components: 'kubectl'

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker Images
        run: |
          docker build -t gcr.io/skavaair/frontend ./frontend
          docker build -t gcr.io/skavaair/backend ./backend
          docker push gcr.io/skavaair/frontend
          docker push gcr.io/skavaair/backend

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials skavaair-kube-cluster --region europe-north1 --project skavaair

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
