name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: skavaair
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest ./frontend
          docker push europe-north1-docker.pkg.dev/skavaair/frontend/frontend:latest

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t europe-north1-docker.pkg.dev/skavaair/backend/backend:latest ./backend
          docker push europe-north1-docker.pkg.dev/skavaair/backend/backend:latest

      - name: Set up kubeconfig
        run: |
          gcloud container clusters get-credentials skavaair-kube-cluster --region europe-north1

      - name: Deploy Frontend to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Deploy Backend to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml

      - name: Deploy MongoDB to Kubernetes
        run: |
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mongo-service.yaml

      - name: Restart Frontend Deployment
        run: |
          kubectl rollout restart deployment frontend-deployment

      - name: Restart Backend Deployment
        run: |
          kubectl rollout restart deployment backend-deployment
